module.exports=function(grunt){
	grunt.initConfig({
		pkg:grunt.file.readJSON('package.json'),
		copy:{
			main:{
				files:[
					{expand:true,cwd:'app/',src:'*.php',dest:'dest/app/',filter:'isFile'},
					{expand:true,cwd:'app/',src:'js/*',dest:'dest/app/',filter:'isFile'},
					{expand:true,cwd:'app/',src:'css/*',dest:'dest/app/',filter:'isFile'},
					{expand:true,cwd:'app/',src:'css/themes/**',dest:'dest/app/',filter:'isFile'},
					{expand:true,cwd:'app/',src:'views/*',dest:'dest/app/',filter:'isFile'},
					{expand:true,cwd:'app/',src:'images/*',dest:'dest/app/',filter:'isFile'},
					{
						expand:true,
						cwd:'app/bower_components/',
						src:'angular/angular.min.js',
						dest:'dest/app/bower_components/',
						filter:'isFile'
					},
					{
						expand:true,
						cwd:'app/bower_components/',
						src:'angular-route/angular-route.min.js',
						dest:'dest/app/bower_components/',
						filter:'isFile'
					},
					{
						expand:true,
						cwd:'app/bower_components/',
						src:'swiper/src/idangerous.swiper.js',
						dest:'dest/app/bower_components/',
						filter:'isFile'
					},
					{
						expand:true,
						cwd:'app/bower_components/',
						src:'angular-sanitize/angular-sanitize.js',
						dest:'dest/app/bower_components/',
						filter:'isFile'
					},
					{
						expand:true,
						cwd:'app/bower_components/',
						src:'videogular/videogular.js',
						dest:'dest/app/bower_components/',
						filter:'isFile'
					},
					{
						expand:true,
						cwd:'app/bower_components/',
						src:'videogular-controls/controls.js',
						dest:'dest/app/bower_components/',
						filter:'isFile'
					},
					{expand:true,src:['server/**'],dest:'dest/'}
				]
			}
		},
		clean:{
			start:{
				src:['dest']
			},
			main:{
				src:['dest/app/views_old','dest/server/mysql']
			}
		},
		uglify:{
			main:{
				options:{
					compress:true
				},
				files:{
					'dest/app/js/login.js':['app/js/login.js'],
					'dest/app/js/password.js':['app/js/password.js']
				}
			}
		}
	});
	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-contrib-cssmin');
	grunt.loadNpmTasks('grunt-cmd-concat');
	grunt.loadNpmTasks('grunt-contrib-copy');
	grunt.loadNpmTasks('grunt-contrib-clean');
	grunt.registerTask('default',['clean:start','copy','clean:main','uglify']);
}
